require_relative '../js/node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

project 'NativeIOSApp/NativeIOSApp.xcodeproj'

target 'NativeIOSApp' do
  use_react_native!(
    :path => '../js/node_modules/react-native',
    :hermes_enabled => true, # React Native 0.81.5 requires Hermes
    :fabric_enabled => false
  )
end

# Configure React Native build settings
post_install do |installer|
  react_native_path = File.join(__dir__, '..', 'js', 'node_modules', 'react-native')
  
  installer.pods_project.targets.each do |target|
    # Set REACT_NATIVE_PATH for all targets (needed for codegen)
    target.build_configurations.each do |config|
      config.build_settings['REACT_NATIVE_PATH'] = react_native_path
    end
  end
  
  # Disable sandbox for embed frameworks build phase in main app target
  main_project_path = File.join(__dir__, 'NativeIOSApp', 'NativeIOSApp.xcodeproj', 'project.pbxproj')
  if File.exist?(main_project_path)
    project_content = File.read(main_project_path)
    # Disable user script sandboxing globally (this is the key setting!)
    project_content = project_content.gsub(
      /ENABLE_USER_SCRIPT_SANDBOXING = YES;/,
      'ENABLE_USER_SCRIPT_SANDBOXING = NO;'
    )
    # Also add disableSandbox = 1 to the embed frameworks build phase
    unless project_content.include?('disableSandbox = 1')
      project_content = project_content.gsub(
        /(shellScript = ".*?Pods-NativeIOSApp-frameworks\.sh.*?";\n\t\t)(showEnvVarsInLog = \d+;)/,
        "\\1disableSandbox = 1;\n\t\t\\2"
      )
    end
    File.write(main_project_path, project_content)
  end
  
  # Also update the script to use cp -R instead of rsync
  frameworks_script_path = File.join(__dir__, 'Pods', 'Target Support Files', 'Pods-NativeIOSApp', 'Pods-NativeIOSApp-frameworks.sh')
  if File.exist?(frameworks_script_path)
    script_content = File.read(frameworks_script_path)
    # Replace rsync commands with cp -R
    script_content = script_content.gsub(
      /rsync --delete -av ".*?" --links --filter.*?"\$\{source\}" "\$\{destination\}"/,
      'rm -rf "$destination/$(basename "$source")" && cp -R "$source" "$destination"'
    ) unless script_content.include?('cp -R "$source" "$destination"')
    File.write(frameworks_script_path, script_content)
  end
end
